name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_HOST }} -u admin --password-stdin
      - name: Build
        run: docker build -t ${{ secrets.DOCKER_HOST }}/slashtags:${{github.sha}} .
      - name: Push
        run: docker push ${{ secrets.DOCKER_HOST }}/slashtags:${{github.sha}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: Set image
        run: kubectl set image deployment/slashtags slashtags=${{ secrets.DOCKER_HOST }}/slashtags:${{github.sha}}
      - name: Rollout status
        run: kubectl rollout status deployment/slashtags
